# https://taskfile.dev

version: '3'

vars:
  VENV_DIR: .venv
  PYTHON: "{{.VENV_DIR}}/bin/python"
  PIP: "{{.VENV_DIR}}/bin/pip"
  UV: "{{.VENV_DIR}}/bin/uv"
  PRECOMMIT: "{{.VENV_DIR}}/bin/pre-commit"

tasks:
  venv:
    desc: "Create Python virtual environment"
    cmds:
      - python -m venv {{.VENV_DIR}} --upgrade --upgrade-deps
      - "{{.PIP}} install --upgrade uv"
    status:
      - test -f {{.UV}}

  install:
    desc: "Install project dependencies"
    deps: [venv]
    cmds:
      - "{{.UV}} pip install -e . --group dev"
    sources:
      - pyproject.toml
    generates:
      - "{{.VENV_DIR}}/lib/python*/site-packages/*"

  add:
    desc: Install one or more packages
    deps: [venv]
    cmds:
      - "{{.UV}} add {{.CLI_ARGS}}"

  add-dev:
    desc: Install one or more dev packages
    deps: [venv]
    cmds:
      - "{{.UV}} add --dev {{.CLI_ARGS}}"

  pre-commit-install:
    desc: Install pre-commit hooks
    deps: [venv]
    cmds:
      - "{{.PRECOMMIT}} install"
    status:
      - test -f .git/hooks/pre-commit

  pre-commit-run:
    desc: Run pre-commit hooks on all files
    deps: [venv]
    cmds:
      - "{{.PRECOMMIT}} run --all-files"

  format:
    desc: Format Python and Jupyter files with ruff
    deps: [venv]
    cmds:
      - "{{.VENV_DIR}}/bin/ruff format ."

  test:
    desc: Run pytest tests
    deps: [venv]
    cmds:
      - "{{.VENV_DIR}}/bin/pytest {{.CLI_ARGS}}"

  api:
    desc: Start the FastAPI server
    deps: [venv]
    cmds:
      - "{{.VENV_DIR}}/bin/uvicorn alyra_ai_ml.api.main:app --reload"

  cli:
    desc: Run the CLI
    deps: [venv]
    cmds:
      - "{{.VENV_DIR}}/bin/alyra-ml {{.CLI_ARGS}}"

  train:
    desc: Train a model
    deps: [venv]
    cmds:
      - "{{.VENV_DIR}}/bin/alyra-ml train {{.CLI_ARGS}}"
