# https://taskfile.dev

version: '3'

vars:
  VENV_DIR: .venv
  PYTHON: "{{.VENV_DIR}}/bin/python"
  PIP: "{{.VENV_DIR}}/bin/pip"
  UV: "{{.VENV_DIR}}/bin/uv"

tasks:
  venv:
    desc: "Create Python virtual environment"
    cmds:
      - python -m venv {{.VENV_DIR}} --upgrade --upgrade-deps
      - "{{.PIP}} install --upgrade uv"
    status:
      - test -f {{.UV}}

  install:
    desc: "Install project dependencies"
    deps: [venv]
    cmds:
      - "{{.UV}} pip install -e ."
    sources:
      - pyproject.toml
    generates:
      - "{{.VENV_DIR}}/lib/python*/site-packages/*"
